In [1]:
import pandas as pd
data = pd.read_csv("D:/ML/Practical/ML Dataset/Bengaluru_House_Data.csv")

In [2]:
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [3]:
data.shape

print(data.head)
print(data.dtypes)

# Drop specified columns
data.drop(['availability', 'location', 'society'], axis=1, inplace=True)
# Display the updated dataframe
print(data.head())

<bound method NDFrame.head of                   area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II
1                Plot  Area  Ready To Move          Chikka Tirupathi
2            Built-up  Area  Ready To Move               Uttarahalli
3      Super built-up  Area  Ready To Move        Lingadheeranahalli
4      Super built-up  Area  Ready To Move                  Kothanur
...                     ...            ...                       ...
13315        Built-up  Area  Ready To Move                Whitefield
13316  Super built-up  Area  Ready To Move             Richards Town
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar
13318  Super built-up  Area         18-Jun           Padmanabhanagar
13319  Super built-up  Area  Ready To Move              Doddathoguru

            size  society total_sqft  bath  balcony   price
0          2 BHK  Coomee        1056   2.0      1.0   39.07
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00
2          3 BHK      NaN       1440   2.0      3.0   62.00
3          3 BHK  Soiewre       1521   3.0      1.0   95.00
4          2 BHK      NaN       1200   2.0      1.0   51.00
...          ...      ...        ...   ...      ...     ...
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00
13316      4 BHK      NaN       3600   5.0      NaN  400.00
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00
13319      1 BHK      NaN        550   1.0      1.0   17.00

[13320 rows x 9 columns]>
area_type        object
availability     object
location         object
size             object
society          object
total_sqft       object
bath            float64
balcony         float64
price           float64
dtype: object
              area_type       size total_sqft  bath  balcony   price
0  Super built-up  Area      2 BHK       1056   2.0      1.0   39.07
1            Plot  Area  4 Bedroom       2600   5.0      3.0  120.00
2        Built-up  Area      3 BHK       1440   2.0      3.0   62.00
3  Super built-up  Area      3 BHK       1521   3.0      1.0   95.00
4  Super built-up  Area      2 BHK       1200   2.0      1.0   51.00

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Initialize LabelEncoder
label_encoder = LabelEncoder()
# Apply label encoding to each categorical column
for col in ['area_type', 'size']:
    if col in data.columns:
        data[col] = label_encoder.fit_transform(data[col].astype(str))
# Display the updated dataframe
print(data.head())

data.isnull().sum() 

# Check for duplicate rows
duplicate_rows_count = data.duplicated().sum()
print("\nNumber of Duplicate Rows:", duplicate_rows_count)

# Replace NaN values in 'bath' column with mode
bath_mode = data['bath'].mode()[0]
data['bath'].fillna(bath_mode, inplace=True)
# Replace NaN values in 'balcony' column with mode
balcony_mode = data['balcony'].mode()[0]
data['balcony'].fillna(balcony_mode, inplace=True)
data.isnull().sum()

# Remove duplicate rows
data.drop_duplicates(inplace=True)
# Check for duplicate rows
duplicate_rows_count = data.duplicated().sum()
print("\nNumber of Duplicate Rows:", duplicate_rows_count) 

data.describe() 

#checking boxplot for Age column
import matplotlib.pyplot as plt
%matplotlib inline
plt.boxplot(data['size'])
plt.show()

#Checking Outlier by definition and treating outliers
#getting median Age
size_col_df = pd.DataFrame(data['size'])
size_median = size_col_df.median()
#getting IQR of Age column
Q3 = size_col_df.quantile(q=0.75)
Q1 = size_col_df.quantile(q=0.25)
IQR = Q3-Q1
#Deriving boundaries of Outliers
IQR_LL = int(Q1 - 1.5*IQR)
IQR_UL = int(Q3 + 1.5*IQR)
#Finding and treating outliers - both lower and upper end
data.loc[data['size']>IQR_UL , 'size'] = int(size_col_df.quantile(q=0.90))
data.loc[data['size']<IQR_LL , 'size'] = int(size_col_df.quantile(q=0.01))

#checking boxplot for Age column
import matplotlib.pyplot as plt
%matplotlib inline
plt.boxplot(data['size'])
plt.show()

#Check how Expense is varying with Age
x = data["size"]
y=  data["price"]
plt.scatter(x, y)
plt.title('size price chart')
plt.xlabel('size')
plt.ylabel('price')
plt.show()

import seaborn as sns
sns.distplot(data['size'])  #to see the distribution

# Assuming data is your DataFrame
# Remove rows where 'total_sqft' cannot be converted to float
data = data[data['total_sqft'].apply(lambda x: str(x).replace('.', '', 1).isdigit())]
# Convert 'total_sqft' column to float
data['total_sqft'] = data['total_sqft'].astype(float)
#checking boxplot for Age column
import matplotlib.pyplot as plt
%matplotlib inline
plt.boxplot(data['total_sqft'])
plt.show()

#Checking Outlier by definition and treating outliers
#getting median Age
size_col_df = pd.DataFrame(data['total_sqft'])
size_median = size_col_df.median()
#getting IQR of Age column
Q3 = size_col_df.quantile(q=0.75)
Q1 = size_col_df.quantile(q=0.25)
IQR = Q3-Q1
#Deriving boundaries of Outliers
IQR_LL = int(Q1 - 1.5*IQR)
IQR_UL = int(Q3 + 1.5*IQR)
#Finding and treating outliers - both lower and upper end
data.loc[data['total_sqft']>IQR_UL , 'total_sqft'] = int(size_col_df.quantile(q=0.90))
data.loc[data['total_sqft']<IQR_LL , 'total_sqft'] = int(size_col_df.quantile(q=0.01))

#checking boxplot for Age column
import matplotlib.pyplot as plt
%matplotlib inline
plt.boxplot(data['total_sqft'])
plt.show()

#Check how Expense is varying with Age
x = data["total_sqft"]
y=  data["price"]
plt.scatter(x, y)
plt.title('total_sqft price chart')
plt.xlabel('total_sqft')
plt.ylabel('price')
plt.show()


import seaborn as sns
sns.distplot(data['total_sqft'])  #to see the distribution

non_numeric_columns = data.select_dtypes(exclude=['number']).columns
print("Non-numeric columns:", non_numeric_columns)


# Calculate the correlation matrix
corr_matrix = data.corr()
# Plot the correlation heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

#Normalization/scaling of data - understanding scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
scaled_data
#converting data back to pandas dataframe
data_scaled = pd.DataFrame(scaled_data)
data_scaled.columns = data.columns
#Separating features and response
features = ["area_type","size", "total_sqft","bath", "balcony"]
response = ["price"]
x=data_scaled[features]
y=data_scaled[response]

#Dividing data in test and train
#Importing neccesary packages
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=0)
#Fitting lineaar regression model
model = LinearRegression()
model.fit(x_train, y_train)
#Checking accuracy on test data
accuracy = model.score(x_test,y_test)
print(accuracy*100,'%')

import numpy as np
y_pred = model.predict(x_test)
print('R2_score : ',metrics.r2_score(y_pred,y_test))
print('MSE : ',metrics.mean_squared_error(y_pred,y_test))

y_test #the actual values in test data - target column

y_pred

print(model.intercept_ ) #checking the intercept of model equation
print(model.coef_)   #Checking the coefficients of model equation